### ISSUE TITLE
WASM: winit issues

### ISSUE THREAD

**Issue by azriel91** [amethyst/amethyst#2211]
Tracking issue for things relating to winit for WASM support.

* impl `Clone` for `'static` Events: https://github.com/rust-windowing/winit/pull/1478
* `wasm-unknown-unknown` support: https://github.com/rust-windowing/glutin/issues/1167
* Double borrow during event handling fix: https://github.com/rust-windowing/winit/pull/1512
* Implement `requestAnimationFrame`: https://github.com/rust-windowing/winit/pull/1519
* Survive OleInitialize failure (for audio): https://github.com/rust-windowing/winit/pull/1524
* web worker support: https://github.com/rust-windowing/winit/issues/1518

My understanding of the situation is rather rough, so simply listing issues.

Yay, with changes from https://github.com/rust-windowing/winit/pull/1512, pong WASM doesn't crash that often:

![pong_wasm_move](https://user-images.githubusercontent.com/2993230/78319041-c35d5380-75c2-11ea-8851-ab294697633c.gif)

**Comment by CleanCut** [comment]
I skimmed through that list real quick -- most items are "merged/resolved"!

* [x] impl `Clone` for `'static` Events: [rust-windowing/winit#1478](https://github.com/rust-windowing/winit/pull/1478)
* [ ] `wasm-unknown-unknown` support: [rust-windowing/glutin#1167](https://github.com/rust-windowing/glutin/issues/1167)
* [x] Double borrow during event handling fix: [rust-windowing/winit#1512](https://github.com/rust-windowing/winit/pull/1512)
* [x] Implement `requestAnimationFrame`: [rust-windowing/winit#1519](https://github.com/rust-windowing/winit/pull/1519)
* [x] Survive OleInitialize failure (for audio): [rust-windowing/winit#1524](https://github.com/rust-windowing/winit/pull/1524)
* [ ] web worker support: [rust-windowing/winit#1518](https://github.com/rust-windowing/winit/issues/1518)
