### ISSUE TITLE
Amethyst 0.16 Release List

### ISSUE THREAD

**Issue by AlveLarsson** [amethyst/amethyst#2308]
### The Legion update
This marks the end for SPECS in amethyst and brings the area of Legion.

### Todo
- [x] Release 0.15.1
- [x] Release 0.15.2
- [x] Release 0.15.3
- [ ] Complete Legion integration: Tracker
- [ ] Merge Legion into master. #2309 
- [ ] Test and fix all examples work with Legion. (catch all)
- [ ] Clean non relevant issues.
- [ ] Clean stale and non relevant branches.
- [ ] Clean done and non relevant projects.
- [ ] Make a migration guide from specs to Legion!
- [ ] [Release & Publish 0.16](https://github.com/amethyst/amethyst/blob/master/docs/PUBLISHING.md)

**Comment by CleanCut** [comment]
Should there be a separate task on https://github.com/amethyst/amethyst/projects/21 for updating the examples in `examples/`, or is that implicitly part of the individual `amethyst_*, complete port` tasks?

**Comment by AlveLarsson** [comment]
Yeah we are using the examples to test the code, but good to have a last catch-all stage after Merge

**Comment by korczis** [comment]
Are there any news? Is still planned to release 0.16? Has the work on amethys stopped? Is there some place where the get fresh news ?
