### ISSUE TITLE
Platforms: Android & IOS

### ISSUE THREAD

**Issue by AlveLarsson** [amethyst/amethyst#2317]
This will track adding Android & IOS support to Amethyst.
This will not be considered official support yet. but can lay the groundwork for it.

Edit:
IOS needs more discussion, but I assume some of the code will be reusable for apple devices like Input, and touch events.

TODO Shared:
- [ ] Moblie cross platforms base?

( More will come here )
### TODO Android:

- [ ] Android NDK, SDK install script, or setup advice.
- [ ] APK creation and install/send it to the device automatically. Preferably one command like `cargo run android`
- [ ] Minimal 2D rendering. 
- [ ] Textured 2D rendering.
- [ ] 3D.
- [ ] Input, and touch events.
- [ ] Network
- [ ] Storage/file access (for assets)

### TODO IOS:
( iOS Devs fill this todo list)

All help and suggestions are welcome! 

legacy issues about this #231 #481

**Comment by jojolepro** [comment]
and also
- network
- storage/file access (for assets)

**Comment by AlveLarsson** [comment]
@jojolepro added your suggestions

**Comment by Blisto91** [comment]
An [upgrade of winit](https://github.com/rust-windowing/winit/blob/master/CHANGELOG.md) is probably essential here.
winit 0.22.2 added minimal platform support for Android.
There have also been a lot of improvements and bug fixes on IOS since 0.19.
