### ISSUE TITLE
Tracking issue - Rename `master` branch to `main`

### ISSUE THREAD

**Issue by khionu** [amethyst/amethyst#2366]
This is a tracking issue for the various tasks that need to be done as part of the branch rename.

- [x] Enact the branch rename
- [ ] Fix links on internet presences
  - [ ] Website
  - [ ] Discord (channel topics, info channels, pins, etc)
  - [ ] Forums
  - [ ] Reddit
  - [ ] Twitter
- [ ] Fix links in documentation
  - [ ] The Amethyst Book
  - [ ] API Documentation
- [ ] Adjust CI

**Comment by CleanCut** [comment]
This might be end up being easier than it sounds.  There's many years-worth of hard-coded links, so GitHub is going to try to handle as many of those cases automatically as it can.  I suggest waiting until GitHub flips the switch on the default branch name before following suit.  It'll save a lot of work.

**Comment by khionu** [comment]
Oh, I thought they had already launched those changes. Alrighty, sure.

**Comment by CleanCut** [comment]
I believe the changes will launch soon.

**Comment by CleanCut** [comment]
For the first time ever, GitHub has released a [public product roadmap](https://github.com/github/roadmap/projects/1).  On that roadmap, there is an item on the Jul-Sep column for [Change the default branch name for new repositories from `master` to `main`](https://github.com/github/roadmap/issues/63) -- that's the place to see when GitHub is "done" making the switch internally and where they will link to documentation.

**Comment by CleanCut** [comment]
GitHub released support for renaming the `master` branch this week. We can move forward with the renaming whenever we're ready.

**Comment by ezpuzz** [comment]
Branch renamed.  Github automatically redirects users.  docs are being linted against it for 0.16 and are out of date on main for legion anyway so no breakage.  I don't have access to any social and @AlveLarsson is in charge of website.
