### ISSUE TITLE
Plan for 0.6 release

### ISSUE THREAD

**Issue by nchashch** [amethyst/amethyst#249]
# Why should we plan?
- Avoid duplication of effort
- Do some architecting in advance
- Implement the most valuable features first
- Set clear goals after accomplishing which we can release 0.6
- Get an idea of how much work is ahead
# How should we plan?
To make it simple I propose:
1. List out all the features we want (it would also be nice to rank them by value/effort ratio)
2. Let developers explicitly claim them (and if they chose to drop the project, the feature would again become "claimable" - with whatever work has already been done before the original developer dropped it already done)

This would serve two purposes:
1. Make duplication of effort very difficult (because areas of work are explicitly claimed)
2. Plan things out in English before writing any code (so we can apply scarce open source developer hours for maximum effect)
# Conclusion
So I think it would be nice to discuss what features we want to implement before 0.6 release in this issue's comments. Then we could compile a final list of features (ranked by value/effort) in the issue itself, and then let people claim features they would like to work on and then during development negotiate dropping and reclaiming the dropped features.

**Comment by Xaeroxe** [comment]
If possible I'd like to get sound effect and music APIs into 0.6.  My first goal is to get 3D audio working in rodio, then integrate rodio into Amethyst.  I know we said in https://github.com/amethyst/amethyst/issues/243 that we didn't really want to make 3D audio in Rust however I wasn't really terribly impressed by the alternatives, as OpenAL isn't exactly Open anymore.  I've got a branch of rodio with super rudimentary audio attenuation that I really just need to upgrade into a more robust and better quality implementation.

Value: High, videogames without sound are kind of a hard sell.
Effort: High, I've found one source with good documentation on how to do 3D audio and it'll be quite a bit of reading for me to sift through before I really know how to do it.

**Comment by vitvakatu** [comment]
Well, I don't know whether it would be possible to bring it into 0.6 release or not, but I'd like to see basic collision detection and basic physics subsystem. I want to use `collision-rs` and maybe `froggy` for that task.

_Value:_ High, we  don't have any collision detection/physics yet and there is no evidence that we can use external libs for this purpose.
_Effort:_ Above average/High. We already have some algorithms in `collision-rs`, we can use experience of `nphysics`. I'm sure I can do this, but I don't know how long will it take.

**Comment by minecrawler** [comment]
Amethyst is still lacking basic 3D camera features. After the renderer rewrite, that should definitely addressed, since without good camera-support, anything 3D will be really hard to implement! I think, the value would be high and the effort small to average (if someone does it who knows how the renderer and the camera work together; though I could do it since I require the camera implementation for my project)

See issue #176

**Comment by Xaeroxe** [comment]
@minecrawler I'd like to hang a small note off of that: One of my future projects (probably won't be here in time for 0.6) is to add 2D sprites and an orthographic camera, so it'd be nice to bundle common functionality between a orthographic camera and perspective camera into a trait.

**Comment by Aceeri** [comment]
I'd like to get rudimentary tooling working for an amethyst editor. This is just normal/medium priority/value and shouldn't be too difficult depending on what we choose for UI tooling.

**Comment by minecrawler** [comment]
@Aceeri what kind of tooling would you like to see? What should be implemented for 0.6?

As for GUI, it would be nice to have something in 0.6, but I would be careful. GUIs can be implemented in wildly different ways. I love to use HTML/CSS/JS for anything GUI, and I would welcome it in Amethyst (would be possible by embedding Servo; though Servo is huuuuuuuge), however other people might prefer other formats or even building a GUI in compiled code. Every implementation might result in a big dependency, so it might make more sense to define traits and add an additional project for a minimal GUI (`amethyst_gui`) which implements those traits. That would allow Amethyst to show off GUI capabilities in examples and anyone can easily get started with a simple GUI, but allow people to switch that thing out later on. Heh, a little GUI library using the ECS and specifically Amethyst would be quite awesome, I guess :D

Well, defining traits is more of a design thing than actual implementation, so I guess the value would be high and the effort would be low. The discussion could be lengthy, so we should open a new issue for that.

**Comment by Xaeroxe** [comment]
Here's my personal wishlist for 0.6, 👍 this if you think this list would be appropriate:

- [ ] GUI implementation https://github.com/amethyst/amethyst/issues/365
- [ ] ECS powered physics framework.  This is currently a competition between [Rhusics](https://github.com/Rhuagh/rhusics) and [nphysics](https://github.com/sebcrozet/nphysics) for which becomes a viable ECS friendly physics system first.
- [ ] Networking module (currently in progress by @LucioFranco @omni-viral and @jojolepro)

That's three major additions to the engine which I feel would warrant a new release.

**Comment by palodequeso** [comment]
Maybe basic OpenVR support? It should be fairly minor compared to those, but substantial none-the-less.

**Comment by Xaeroxe** [comment]
@palodequeso I could work on this, as in a moment of lunacy I did actually buy a Vive, but it's fairly low on my priority list at the moment.  I wouldn't be opposed to it being added but I personally probably won't be working on it until post 1.0.

**Comment by jojolepro** [comment]
My wishlist is almost the same as @Xaeroxe 
(In preference/priority order)
1) State local dispatcher. (In Progress)
2) GUI
3) Physics (In Progress?)
4) Networking (In Progress)
I think once we have those features, it will become possible to make actual games (instead of minimal examples).

**Comment by Rhuagh** [comment]
rhusics has "engine integration", it has `System` implementations for collision detection and spatial sorting so far.

**Comment by omni-viral** [comment]
I'd like to add to the list
-[ ] Skeletal animation system

**Comment by torkleyy** [comment]
I think there are many good points listed here, but I wouldn't consider them a requirement for releasing a new version. I'm proposing to prepare for release.

## What's left

* [ ] #460 
* [ ] #462 
* [ ] #464 

## After that

* [ ] Update changelog
* [ ] Publish new versions
* [ ] Update tool to use 0.6
* [ ] Create an announcement

**Comment by torkleyy** [comment]
While both physics and UI would be nice to have, they won't (shouldn't) be breaking changes.

**Comment by Rhuagh** [comment]
I'm on favor. Might want the animation in there though? It's done, and can be used for camera animation and such now. The missing parts are skinning, and that'll come later, but is decoupled completely from animation.

**Comment by erlend-sh** [comment]
Looks like the 0.6 release has been tagged 🎉 

https://github.com/amethyst/amethyst/releases/tag/v0.6.0

I still think it'd be worthwhile to have a bare-bones changelog for the release page as well as for a blog post on amethyst.rs. There's plenty of tools that can automate this for you:

- https://github.com/lob/generate-changelog
- https://github.com/skywinder/github-changelog-generator
- https://github.com/conventional-changelog/conventional-changelog

Also ought to post about this on https://www.reddit.com/r/rust_gamedev/

**Comment by Xaeroxe** [comment]
@erlend-sh thanks for the changelog generators!  And yes we have a blog post about the release in the works.  It should be finished fairly soon and then we'll post it to reddit.

**Comment by Rhuagh** [comment]
All the changelog generators require a specific commit format though, so they're hard to apply after the fact.

**Comment by Xaeroxe** [comment]
0.6 is out, so I'm closing this!
