### ISSUE TITLE
Pong tutorial progress!

### ISSUE THREAD

**Issue by futurepaul** [amethyst/amethyst#506]
Here's the todo list for the pong tutorial, let me know if there's anything you'd like to add.

- [x] Opening and closing a window (explaining State) #495 
- [x] Drawing the paddles (explaining Entities) #495 
- [x] Moving the paddles (explaining Systems) #507 
- [x] Adding a moving ball (revising the previous two chapters)
- [x] Adding a win-condition (explaining creating Components)
- [x] Adding score (explaining Resources & UI)
- [ ] Audio (Resources and Audio)

I think it would be nice to do a very simple walkthrough of the rendering pass somewhere in here, where we recreate the built-in pass (`DrawFlat::<PosTex>`) we're using right now. Does that sound reasonable?

**Comment by Rhuagh** [comment]
Recreating the pass might be a bit challenging, it's not the simplest code out there :)

**Comment by trsoluti** [comment]
Hi, my name is Thomas and I'm interested in helping out with the documentation as well. I've had some experience with COP--you can check out my C# implementation in trsoluti/SDL2-CS-COP.

Here's the list of things that I was thinking (independently of @futurepaul) needed to be documented for explaining Pong (i.e. the steps to build a full Pong application from the basic example with emphasis on explaining how COP works):

- [ ] Create  & run new example
- [ ] Do some simple cleanup:
    - [ ] Update display_config.ron
    - [ ] Change “Example” to “Pong” 
    - [ ] Move Pong to own file & import only what is necessary
    - [ ] Modify the asset-loading pipe
    - [ ] Divide up the game builder so it looks more like the one in the pong example
- [ ] Create a simple component with bundle
    - [ ] Add the ball component to main.rs
    - [ ] Add the pong bundle, and put the ball in it
    - [ ] Add the pong bundle (+any anything necessary to get it to run) to the game builder
- [ ] Show a ball object [Lots of code not related to COP--can we put this in a separate file the user can just copy and paste?]
    - [ ] Identify the constants that will be needed
    - [ ] Create the mesh
    - [ ] Create the material
    - [ ] Generate circles
    - [ ] Create the ball
    - [ ] Initialise the ball in the on_start event
    - [ ] Initialise the camera in the on_start event
- [ ] Get the ball to move:
    - [ ] Add Systems folder and move_balls system
    - [ ] Add MoveBallsSystem to builder in bundle
- [ ] Get the ball to stay in the court
    - [ ] Add BounceSystem to systems
    - [ ] Add the top-and-bottom-margin bounces (no sound)
    - [ ] Add BounceSystem to bundler in bundle
    - [ ] Set ball velocity x to 5.9 so we can test bouncing on top (and on paddles, later)
- [ ] Add paddles
    - [ ] Add paddle constants to main.rs
    - [ ] Create the paddle component in main.rs
    - [ ] Register the paddle component in bundle.rs
    - [ ] Add the code in pong.rs to draw the paddle
    - [ ] Add the code in pong.rs to initialise the paddle
- [ ] Get ball to bounce off paddles
    - [ ] Add paddles to bounce system data
    - [ ] Add method to test if point is in box
    - [ ] Add collision check
- [ ] Make paddle move
    - [ ] Add input.ron (key bindings)
    - [ ] Add input bundle to game builder
    - [ ] Add paddle system to systems
    - [ ] Add paddle system to pong bundle (order matters, right?)
- [ ] Add scoreboard
    - [ ] Make sure UI is available and added to world in main.rs
    - [ ] Add scoreboard component in main.rs
    - [ ] Register scoreboard component in bundle.rs
    - [ ] Add initialise_score in pong.rs
    - [ ] Add initialise_score, hide_cursor to on_start in pong.rs 
- [ ] Add sound effects and background sound
- [ ] Add frame limit strategy (? where's the best place to do this?)

Does this help, @futurepaul ?

Thomas.

**Comment by torkleyy** [comment]
Isn't this outdated now @jojolepro ? Or are those still valid for the new tutorial?

**Comment by raydenuni** [comment]
I just went through the tutorial and found a minor issue. In chapter 5, the text mentions the 8th argument of  UiTransform, the tab_order, but the code snippet doesn't have it and won't compile.

https://www.amethyst.rs/book/master/pong-tutorial/pong-tutorial-05.html
https://docs.rs/amethyst_ui/0.4.0/amethyst_ui/struct.UiTransform.html

**Comment by torkleyy** [comment]
Thanks @raydenuni for reporting!

**Comment by golergka** [comment]
Both checklists in this issue seem a bit outdated. What's the current status of the tutorial and how can I contribute?

**Comment by torkleyy** [comment]
> Both checklists in this issue seem a bit outdated. What's the current status of the tutorial and how can I contribute?

Updated the first checklist. We're still missing:

* scores
* audio

**Comment by kylejlin** [comment]
Hi! I would be happy to write a chapter on audio. Should I immediately start working on a fork, or is there some tutorial-writing guidelines I should read first? I have already read CONTRIBUTING.md.

**Comment by azriel91** [comment]
Hiya @kylejlin, thank you for offering!

We haven't formalized tutorial-writing guidelines, so feel free to start on a fork. Personally [this blog post](https://www.divio.com/blog/documentation/) has become one of my "go to"s when I begin to write something.

At some point in the future<sup>:tm:</sup>, we'll look at [standardizing the book's content](https://community.amethyst.rs/t/mdbook-going-forwards/234). Just not sure how soon that future is -- life keeps us doing other things like eating :hamburger:.

**Comment by kylejlin** [comment]
Cool! I'll get right to it. Thanks for the links.

**Comment by jojolepro** [comment]
I think the only thing left to do to consider the pong example as complete is to add the audio chapter. 
As such, I'll schedule this issue to be completed (hopefully) before the next release.

:tada:

**Comment by kylejlin** [comment]
When I finish writing the chapter (hopefully in the near future), what branch should I commit to? Or should I create a new branch?

**Comment by jojolepro** [comment]
Commit in a new branch in your fork (created with the button at the top, middle-right of this page), then you'll have the option to open a "pull request" to merge your branch into amethyst.

**Comment by kylejlin** [comment]
My first draft is finished! Take a look at #1842.

Your feedback is welcome and would be greatly appreciated 😊.

**Comment by kylejlin** [comment]
Should we close this issue now that #1842 has been merged?

**Comment by azriel91** [comment]
Yeaps! Thank you :bowing_man:

**Comment by jojolepro** [comment]
Thanks!!!

**Comment by kylejlin** [comment]
No problem, happy to help! Thanks for your continuous support!
