### ISSUE TITLE
Release 0.7

### ISSUE THREAD

**Issue by Xaeroxe** [amethyst/amethyst#553]
There are several bug fixes and general usability improvements in [here](https://github.com/amethyst/amethyst/compare/release-0.6...develop).  I feel this warrants releasing a 0.7 version.

I'll plan on doing this sometime in early February unless there are dissenting opinions on doing a release.

**Comment by Rhuagh** [comment]
Sound good

**Comment by torkleyy** [comment]
I'd love to get Specs 0.11 in there, but.. PRs are still not merged :(

**Comment by jojolepro** [comment]
Looks fine

**Comment by Xaeroxe** [comment]
Opinion time: Should we wait for an example that can use 2D sprites before we release 0.7?  I think this is a great milestone to achieve before a release, but I worry because this kind of logic can cause there to be months between our releases.

**Comment by torkleyy** [comment]
We want to get the next Specs version in anyways, so as long as it isn't out, why not try to add it?

**Comment by huhlig** [comment]
Not sure if direct dependency or indirect but ron-rs also had a version release.

**Comment by shulcsm** [comment]
Is there an ETA or roadmap?

**Comment by jojolepro** [comment]
Waiting for a new specs release.

**Comment by shulcsm** [comment]
specs has been released

**Comment by Rhuagh** [comment]
Yep, we are mostly cleaning up and finishing stuff at this point I'd say.

**Comment by Rhuagh** [comment]
Remaining issues that should probably be finished before we can release:

- [ ] Prefab loading
- [ ] Localisation Wrapper
- [ ] Use glsl-layout
- [ ] Swap to `failure` instead of `error-chain`
- [ ] Make fly camera use `DeviceEvent`
- [ ] Make examples main functions use `Result` directly
- [ ] Enhance README, and add Issue templates
- [ ] Do an overview of the state of code documentation
- [ ] Do an overview of the book
- [ ] Get bugfix for `coreaudio-sys` released

**Comment by Rhuagh** [comment]
True, I guess, but the bugfix in `coreaudio-sys` is kind of a breaker.
