### ISSUE TITLE
0.7 release

### ISSUE THREAD

**Issue by antoninklopp** [amethyst/amethyst#677]
Hi! 

I just discovered amethyst, and I would really like to start making games with it. 

A lot of things have changed in the engine recently and it seems to me that a lot of things in the code are new compared to the early January release. 

(I hope I am posting my question in the good place).

**Comment by Xaeroxe** [comment]
Yes, I'm itching to do a release.  We got a few more Integrations and finalizations that we need to complete, and then we should be ready for a release.

**Comment by derekdreery** [comment]
If you follow PRs, you can use develop branch.

**Comment by torkleyy** [comment]
@jojolepro You mean 0.11?

**Comment by jojolepro** [comment]
yes :P

**Comment by Xaeroxe** [comment]
@amethyst/engine-devs @jojolepro @Rhuagh I'd like to do a 0.7 release.  Here's my personal wishlist of things to merge before we do this.

- [ ] https://github.com/amethyst/amethyst/pull/719
- [ ] https://github.com/amethyst/amethyst/pull/718
- [ ] https://github.com/amethyst/amethyst/pull/716
- [ ] https://github.com/amethyst/amethyst/pull/704

**Comment by Rhuagh** [comment]
We now have 2 "0.7 release" issues ?

**Comment by Rhuagh** [comment]
Duplicate of #553 ?

**Comment by Rhuagh** [comment]
Prefab loading should be postponed, it will be some time before I'm done with that.

**Comment by Xaeroxe** [comment]
Prefab loading will be postponed then.  And with that I think we're ready!  I'll make sure to close #553 too.

**Comment by Rhuagh** [comment]
We should do a review of the docs before release, imho. And coreaudio-sys is still not released, and I don't have access over there yet :/

**Comment by jojolepro** [comment]
I have 2 days of exams then a ton of free time until I get a job, so I should be able to get through the locale and networking PR this weekend. I'd like them to be in 0.7 if possible.

**Comment by Rhuagh** [comment]
If we release now, we need to update the README with clear instructions on how to fix the audio issue.

**Comment by torkleyy** [comment]
@jojolepro I don't think we should block on feature PRs, we want to do more releases. Blocking on them will prohibit that.

**Comment by jojolepro** [comment]
okay

**Comment by torkleyy** [comment]
I think those PRs are non-breaking anyway, right?

**Comment by jojolepro** [comment]
yep they don't break anything

**Comment by Xaeroxe** [comment]
@Rhuagh

> how to fix the audio issue.

Sorry I wasn't aware of an audio issue, can you clarify?

**Comment by Xaeroxe** [comment]
Oh dur

**Comment by Xaeroxe** [comment]
My bad I remember now.  Yeah we'll have to do something about that.
